@startuml

	!define	S_EMC_CHARGE	'R6-PT5CHG-EM'
	!define	FLOW_TOT	'ignore'
	!define	FLOW_VLV1	'CV-2121'
	!define	FLOW_CTL	'ignore'
	!define	CHG_SP	'R6-PT5CHG-EM/OP001'
	!define	RX_TARE	'ignore'
	!define	good_charge_target	1000
	!define	bad_charge_target	1

@enduml