@startuml

!define	S_EMC_CHARGE	'R9-WTRCHG-EM'
!define	FLOW	'FI-2431'
!define	FLOW_VLV1	'CV-2431'
!define	FLOW_TOT	'FQIC-2431/TOTAL'
!define CHG_SP   'R9-WTRCHG-EM/OP001'
!define RX_TARE		'ignore'
!define good_charge_target		1000
!define bad_charge_target		5

@enduml