!define RX_AGITATOR_CM  HS-1657
!define TEMP_HEAT   2
@startuml

state Coco_Oil{

[*] --> coco_Start_Agitate
coco_Start_Agitate: Start 'RX_AGITATOR_CM'
coco_Start_Agitate: Set'RX_AGITATOR_CM/SPEED_RSP' to 80%

coco_Start_Agitate --> coco_Steam_Heat
coco_Steam_Heat: Set 'RX_JKT_CTRL_EM/A_COMMAND' to TEMP_HEAT

coco_Steam_Heat --> [*]

}

@enduml