@startuml

state Initialize{
[*] --> Initialize_CloseAll
Initialize_CloseAll: Close 'RX_RFLXFLOW_CM' to 0%
Initialize_CloseAll: Close 'HO_CTL_VLV' to 0
Initialize_CloseAll: Close 'STM_CTL_VLV'
Initialize_CloseAll: Close 'TO_SPLY_VLV'
Initialize_CloseAll: Close 'TO_CTL_VLV' to 0
Initialize_CloseAll: Close 'TO_RTN_VLV'
Initialize_CloseAll: Close 'CW_SPLY_VLV'
Initialize_CloseAll: Close 'CW_RTN_VLV'
Initialize_CloseAll: Close 'CW_CTL_VLV' to 100%
Initialize_CloseAll: Close 'TJ_VLV'
Initialize_CloseAll: Close 'MJ_VLV'
Initialize_CloseAll: Close 'BJ_VLV'
Initialize_CloseAll: Close 'BC_VLV'
Initialize_CloseAll: Close 'TC_VLV'
Initialize_CloseAll: Stop 'RX_VACUUM'

Initialize_CloseAll --> Initialize_Blowdown
Initialize_Blowdown: Set 'RX_JKT_CTRL_EM/A_COMMAND' to TEMP_BLOWDOWN

Initialize_Blowdown --> Initialize_Tare
Initialize_Tare: Set 'RX_TARE1/RESET_TOT' to True
Initialize_Tare: Set 'RX_TARE2/RESET_TOT' to True

Initialize_Tare --> Initialize_OAR_Confirm
Initialize_OAR_Confirm: OAR message: "Reactor must be clean. Open manual valves for AEEA and CFA.\n\
Open cooling water flow to condenser. Charge water to decanter. \n\
Setup decanter pump to reflux to column."

Initialize_OAR_Confirm --> Initialize_Complete: OAR response = ok
Initialize_Complete: OAR message: "Ready to start charging raw materials?"

Initialize_Complete --> [*]: OAR response = ok

}

@enduml