@startuml

!define	ALIAS	ignore
!define	BISULFITE_CM	CV-4272
!define	BT4_AGIT_CM	ignore
!define	BT4_CHG_EM	ignore
!define	BT4_CHG_TOT	ignore
!define	BT4_CHG_VLV	ignore
!define	BT4_STMVLV_CM	ignore
!define	BT4_TEMPERATURE	ignore
!define	CLEANOUT_CM	ignore
!define	COND_BLOCK_VLV	CV-4267
!define	COND_FLOWVLV_CM	FIC-4267
!define	DUMMY	ignore
!define	EXT_ARB_MOD	ALK-ARBITRATION
!define	HCL_CHG_EM	HCLCHG-EM
!define	HCL_CHG_TOT	FQIC-2086
!define	HCL_CHG_VLV	CV-4275
!define	INTERM_CHG_EM	ignore
!define	OVHD_CHG_EM	R10-OVHCHG-EM
!define	OVHD_CHG_VLVM	ignore
!define	OVHD_CHG_VLVRX	CV-4280
!define	PPW_CHG_VLV	CV-4289
!define	PT5_CHG_EM	ignore
!define	PT5_CHG_TOT	ignore
!define	PT5_CHG_VLV	ignore
!define	PT5_WEIGHT	WI-1564
!define	PT7_CHG_EM	ignore
!define	PT7_CHG_TOT	ignore
!define	PT7_CHG_VLV	ignore
!define	RECIRC_VLV_CM	CV-4274
!define	RX_AGITATOR_CM	HS-4266
!define	RX_CAUS_SCRUB_CM	ignore
!define	RX_DISCHVLV_CM	CV-4690
!define	RX_PH	AI-4261
!define	RX_PH_ADJ	AI-4261_ADJ
!define	RX_PRESS_EM	R10-PRES-EM
!define	RX_PRESSURE	PIC-4264B
!define	RX_TARE1	WI-4260_TARE1
!define	RX_TARE2	WI-4260_TARE2
!define	RX_TEMP_CTRL_EM	R10-TEMP-EM
!define	RX_TEMPERATURE	TI-4263
!define	RX_VENT	PIC-4264A
!define	RX_WEIGHT	WI-4260
!define	RX_XFR_PUMP_CM	HS-4276
!define	SPRAYBALL_CM	CV-4263D
!define	THISUNIT	R10-BATCH
!define	TK13_CHG_EM	TK13CHG-EM
!define	TK13_CHG_PMP	HS-4628
!define	TK13_CHG_TOT	FQIC-4630
!define	TK13_CHG_VLV	CV-4291
!define	TK13_LVL	LI-2053
!define	TK13_WEIGHT	WI-2053
!define	TK14_CHG_EM	TK14CHG-EM
!define	TK14_CHG_TOT	FQIC-4631
!define	TK14_CHG_VLV	CV-4283
!define	TK14_LVL	LI-2064
!define	TK14_WEIGHT	WI-2064
!define	TK15_CHG_EM	TK15CHG-EM
!define	TK15_CHG_TOT	FQIC-4632
!define	TK15_CHG_VLV	CV-4277
!define	TK15_LVL	LI-4633
!define	TK15_WEIGHT	WI-4633
!define	TK17_CHG_EM	TK17CHG-EM
!define	TK17_CHG_TOT	FQIC-4675
!define	TK17_CHG_VLV	CV-4279
!define	TK17_LVL	LI-4676
!define	TK17_WEIGHT	WI-4676
!define	TK1_CHG_EM	ignore
!define	TK1_CHG_TOT	FQIC-2609
!define	TK1_CHG_VLV	ignore
!define	TK1_LVL	LI-2604
!define	TK1_WEIGHT	WI-2604
!define	TK2_CHG_EM	R10-TK2CHG-EM
!define	TK2_CHG_TOT	FQIC-2623
!define	TK2_CHG_VLV	CV-2623
!define	TK2_LVL	LI-2620
!define	TK2_WEIGHT	WI-2620
!define	TK36_CHG_EM	R10-TK36CHG-EM
!define	TK36_CHG_TOT	FQIC-4268
!define	TK36_CHG_VLV	CV-4268
!define	TK36_LVL	LI-2163
!define	TK36_SRC_EM	TK36-SRC-EM
!define	TK36_WEIGHT	WI-2163
!define	TK50_CHG_EM	R3-TK50CHG-EM
!define	TK50_CHG_TOT	FQIC-4270
!define	TK50_CHG_VLV	CV-4270
!define	TK50_LVL	LI-245
!define	TK50_SRC_EM	TK50-SRC-EM
!define	TK50_WEIGHT	WI-245
!define	TK57_CHG_EM	TK57CHG-EM
!define	TK57_CHG_VLV	CV-4272
!define	TK57_LVL	LI-203
!define	TK58_CHG_EM	ignore
!define	TK58_CHG_TOT	ignore
!define	TK58_CHG_VLV	ignore
!define	TK58_LVL	LI-251
!define	TK58_WEIGHT	WI-251
!define	TK8_CHG_EM	R10-TK8CHG-EM
!define	TK8_CHG_TOT	FQIC-580
!define	TK8_CHG_VLV	CV-580
!define	TK8_LVL	LI-581
!define	TK8_WEIGHT	WI-581
!define	UNIT_SUPPORT	R10-USM
!define	UV_CHG_EM	R10-UVCHG-EM
!define	UV_CHG_TOT	FQIC-4278
!define	UV_CHG_VLV	CV-4278
!define	WTR_CHG_EM	R10-WTRCHG-EM
!define	WTR_CHG_TOT	FQIC-4289
!define	WTR_CHG_VLV	CV-4289

!define RX_JKT_CTRL_EM  RX_TEMP_CTRL_EM

@enduml