@startuml

!define	ALIAS	ignore
!define	BISULFITE_CM	ignore
!define	BT4_AGIT_CM	HS-2358
!define	BT4_CHG_EM	BT4CHG-EM
!define	BT4_CHG_TOT	FQIC-2351
!define	BT4_CHG_VLV	CV-3026
!define	BT4_STMVLV_CM	CV-1627
!define	BT4_TEMPERATURE	TI-1627
!define	CLEANOUT_CM	ignore
!define	COND_BLOCK_VLV	CV-2412
!define	COND_FLOWVLV_CM	FIC-2396
!define	DUMMY	ignore
!define	EXT_ARB_MOD	ALK-ARBITRATION
!define	HCL_CHG_EM	HCLCHG-EM
!define	HCL_CHG_TOT	FQIC-2086
!define	HCL_CHG_VLV	CV-3015
!define	INTERM_CHG_EM   ignore
!define	OVHD_CHG_EM	R6-OVHCHG-EM
!define	OVHD_CHG_VLVM	CV-2119
!define	OVHD_CHG_VLVRX	CV-3019
!define	PPW_CHG_VLV	CV-3008
!define	PT5_CHG_EM	R6-PT5CHG-EM
!define	PT5_CHG_TOT	FQIC-2121
!define	PT5_CHG_VLV	CV-2121
!define	PT5_WEIGHT	WI-1564
!define	PT7_CHG_EM	PT7CHG-EM
!define	PT7_CHG_TOT	FQIC-2711
!define	PT7_CHG_VLV	CV-3027
!define	RECIRC_VLV_CM	ignore
!define	RX_AGITATOR_CM	HS-3000
!define	RX_CAUS_SCRUB_CM	CV-3028
!define	RX_DISCHVLV_CM	ignore
!define	RX_PH	AI-3005
!define	RX_PH_ADJ	AI-3005_ADJ
!define	RX_PRESS_EM	R6-PRES-EM
!define	RX_PRESSURE	PIC-3002A
!define	RX_TARE1	WI-2120_TARE1
!define	RX_TARE2	WI-2120_TARE2
!define	RX_TEMP_CTRL_EM	R6-TEMP-EM
!define	RX_TEMPERATURE	TI-3004
!define	RX_VENT	PIC-3002B
!define	RX_WEIGHT	WI-2120
!define	RX_XFR_PUMP_CM	HS-2116
!define	SPRAYBALL_CM	CV-3011C
!define	THISUNIT	R6-BATCH
!define	TK13_CHG_EM	TK13CHG-EM
!define	TK13_CHG_PMP	HS-4628
!define	TK13_CHG_TOT	FQIC-4630
!define	TK13_CHG_VLV	CV-3024
!define	TK13_LVL	LI-2053
!define	TK13_WEIGHT	WI-2053
!define	TK14_CHG_EM	TK14CHG-EM
!define	TK14_CHG_TOT	FQIC-4631
!define	TK14_CHG_VLV	CV-3025
!define	TK14_LVL	LI-2064
!define	TK14_WEIGHT	WI-2064
!define	TK15_CHG_EM	TK15CHG-EM
!define	TK15_CHG_TOT	FQIC-4632
!define	TK15_CHG_VLV	CV-3017
!define	TK15_LVL	LI-4633
!define	TK15_WEIGHT	WI-4633
!define	TK17_CHG_EM	TK17CHG-EM
!define	TK17_CHG_TOT	FQIC-4675
!define	TK17_CHG_VLV	CV-3018
!define	TK17_LVL	LI-4676
!define	TK17_WEIGHT	WI-4676
!define	TK1_CHG_EM	TK1CHG-EM
!define	TK1_CHG_TOT	FQIC-2609
!define	TK1_CHG_VLV	CV-3023
!define	TK1_LVL	LI-2604
!define	TK1_WEIGHT	WI-2604
!define	TK2_CHG_EM	ignore
!define	TK2_CHG_TOT	ignore
!define	TK2_CHG_VLV	ignore
!define	TK2_LVL	LI-2620
!define	TK2_WEIGHT	WI-2620
!define	TK36_CHG_EM	R6-TK36CHG-EM
!define	TK36_CHG_TOT	FQIC-4684
!define	TK36_CHG_VLV	CV-4685
!define	TK36_LVL	LI-2163
!define	TK36_SRC_EM	TK36-SRC-EM
!define	TK36_WEIGHT	WI-2163
!define	TK50_CHG_EM	R6-TK50CHG-EM
!define	TK50_CHG_TOT	FQIC-2208
!define	TK50_CHG_VLV	CV-2202
!define	TK50_LVL	LI-245
!define	TK50_SRC_EM	TK50-SRC-EM
!define	TK50_WEIGHT	WI-245
!define	TK57_CHG_EM	ignore
!define	TK57_CHG_VLV	ignore
!define	TK57_LVL	LI-203
!define	TK58_CHG_EM	TK58CHG-EM
!define	TK58_CHG_TOT	FQIC-2444
!define	TK58_CHG_VLV	CV-3029
!define	TK58_LVL	LI-251
!define	TK58_WEIGHT	WI-251
!define	TK8_CHG_EM	ignore
!define	TK8_CHG_TOT	ignore
!define	TK8_CHG_VLV	ignore
!define	TK8_LVL	LI-581
!define	TK8_WEIGHT	WI-581
!define	UNIT_SUPPORT	R6-USM
!define	UV_CHG_EM	R6-UVCHG-EM
!define	UV_CHG_TOT	FQIC-3006
!define	UV_CHG_VLV	CV-3006
!define	WTR_CHG_EM	R6-WTRCHG-EM
!define	WTR_CHG_TOT	FQIC-3008
!define	WTR_CHG_VLV	CV-3008


!define RX_JKT_CTRL_EM  RX_TEMP_CTRL_EM

@enduml