@startuml

title R10-WTRCHG-EM

!define EM_NAME R10-WTRCHG-EM

!define OAR_RESPONSE 'EM_NAME/MONITOR/OAR/INPUT'

!define	S_EMC_CHARGE	'R10-WTRCHG-EM'

!define	FLOW	'FI-4289'
!define	FLOW_VLV1	'CV-4289'
!define	FLOW_TOT	'FQIC-4289/TOTAL'
!define RX_TARE		'ignore'

!define CHG_SP   'EM_NAME/OP001'
!define LOW_CHG_SP 'EM_NAME/OP001_MIN'

!define good_charge_target		1000
!define bad_charge_target		5

@enduml