@startuml

	!define	S_EMC_CHARGE	'R6-UVCHG-EM'
	!define	FLOW_TOT	'FQIC-3006/TOTAL'
	!define	FLOW_VLV1	'CV-3006'
	!define	FLOW	'FI-3006'
	!define	CHG_SP	'R6-UVCHG-EM/OP001'
	!define	RX_TARE	'ignore'
	!define	good_charge_target	1000
	!define	bad_charge_target	5

@enduml