@startuml
title THISUNIT/PH_AL_RCT_NAOH1
!define reaction_temp_setpoint   'RX_JKT_CTL_EM/OP001_VALUE'
!define charge_flow_rate    'TK50_CHG_EM/OP002_VALUE'
!define charge_setpoint ;TK50_CHG_EM/OP001_VALUE'
!define TEMP_AUTO   4
!define CHARGE_CHARGE   2

@enduml