
Definitions for all of the instances in this EM class enclosed in the Definitions folder.
Use a !include <instance path> to substitute Aliases/Parameter_path in this flowchart.
i.e. copy this to the code:
!include Definitions/S_EMC_CHARGE/R10-WTRCHG-EM.puml

@startuml

state CHARGE {
!define good_charge_target 1000
!define bad_charge_target 5

[*] --> StartEM
StartEM: Set S_EMC_CHARGE to CHARGE

StartEM --> OAR_ChargeTarget: Verify S_EMC_CHARGE is in CHARGE and \n FLOW_TOT = 0 and CHG_TGT = 0

OAR_ChargeTarget --> ValveOpened: Set OAR Input to good_charge_target
OAR_ChargeTarget --> NotCharge: Set OAR Input to bad_charge_target

NotCharge: Verify S_EMC_CHARGE not in CHARGE

ValveOpened: Verify FLOW_VLV1 Open

ValveOpened --> ChargeComplete: Wait for FLOW_TOT >= CHG_TGT

ChargeComplete --> [*]: Verify FLOW_VLV1 Closed and S_EMC_CHARGE in CHARGE complete
NotCharge --> [*]

}

state CLOSE_ALL{
[*] --> Set_EM_Close
Set_EM_Close: Set S_EMC_CHARGE to CLOSE ALL

Set_EM_Close --> [*]: Verify FLOW_VLV1 Closed and S_EMC_CHARGE in CLOSE ALL complete

}
@enduml

# CHG_TGT is an OP, it can be read/write with OtherAttribute
# FLOW_TOT can be OtherAttribute too, or IndicationAttribute if declare tag = 'FQIC-####' and attr_path = 'TOTAL'
# FLOW_VLV1 is PositionAttribute