!include  Definitions/S_EMC_PRESS_CND/R1-PRES-EM.puml
!include  Definitions/S_EMC_PRESS_CND/R4-PRES-EM.puml

@startuml

!include  Definitions/S_EMC_PRESS_CND/R4-PRES-EM.puml


state PRESSRE_UP {

[*] --> Check_RX_Pressure
Check_RX_Pressure --> [*]: PRESS_GAP_CTL > pressure_setpoint
Check_RX_Pressure --> Check_VAC_Pump: PRESS_GAP_CTL < pressure_setpoint

Check_VAC_Pump --> OAR_TurnOff: VAC_PMP is running
Check_VAC_Pump --> ValvePosition1: VAC_PMP is stopped

OAR_TurnOff: OAR = INFO
OAR_TurnOff --> ValvePosition1: VAC_PMP is stopped

ValvePosition1: Close SCRUB_VENT_VLV
ValvePosition1: Close DECANT_VENT_VLV
ValvePosition1: Open nitrogen_valve

ValvePosition1 --> Complete: PRESS_GAP_CTL > pressure_setpoint
Complete: Close nitrogen_valve

Complete --> [*]

}


state START_VACUUM {

[*] --> ValvePosition2
ValvePosition2: Close SCRUB_VENT_VLV
ValvePosition2: Close DECANT_VENT_VLV
ValvePosition2: Open VAC_KO_SCRUB

ValvePosition2 --> StartVAC
StartVAC: Start VAC_PMP

StartVAC --> ResetLO
ResetLO: SCRUB_VENT_VLV interlock reset
ResetLO: DECANT_VENT_VLV interlock reset
ResetLO: VAC_KO_SCRUB interlock reset

ResetLO --> Open_VAC_CTRL_Valve

Open_VAC_CTRL_Valve: Set VAC_CTL to control_valve_position in ROUT

Open_VAC_CTRL_Valve --> [*]

}

state STOP_VACUUM {

[*] --> Close_VAC_CTRL_Valve
Close_VAC_CTRL_Valve: Set VAC_CTL to 0%

Close_VAC_CTRL_Valve --> Close_STM_Vlv
Close_STM_Vlv: Close VAC_STM_VLV

Close_STM_Vlv --> Stop_VAC
Stop_VAC: Stop VAC_PMP

Stop_VAC --> Close_Discharge_Vlv
Close_Discharge_Vlv: Close VAC_KO_SCRUB

Close_Discharge_Vlv --> [*]

}

state VENT {

[*] --> Check_RX_Press

Check_RX_Press --> [*]: PRESS_GAP_CTL > pressure_setpoint
Check_RX_Press --> ValvePosition3

ValvePosition3: Close nitrogen_valve
ValvePosition3: Open DECANT_VENT_VLV

ValvePosition3 --> Close_Decant: Wait for PRESS_GAP_CTL < target_pressure

Close_Decant: Close DECANT_VENT_VLV

Close_Decant --> [*]

}

state DEAERATE {

[*] --> ValvePosition4
ValvePosition4: Close SCRUB_VENT_VLV
ValvePosition4: Close DECANT_VENT_VLV
ValvePosition4: Open VAC_KO_SCRUB

ValvePosition4 --> Start_VAC
Start_VAC: Start VAC_PMP
Start_VAC: Set VAC_CTL to control_valve_position in ROUT

Start_VAC --> Ramp_VAC
Ramp_VAC: Set 'VAC_RAMP/RAMP_RATE' to ramp_rate
Ramp_VAC: Set 'VAC_RAMP/RAMP_PAUSE' to False
Ramp_VAC: Set 'VAC_RAMP/RAMP_ENABLE' to True

Ramp_VAC --> STOP_VAC: PRESS_GAP_CTL < ramp_target
STOP_VAC: Stop VAC_PMP
STOP_VAC: Close VAC_STM_VLV
STOP_VAC: Set VAC_CTL to 0

STOP_VAC --> Press_Up

state Press_Up {


OpenN2VLV: Open nitrogen_valve

OpenN2VLV --> CloseN2VLV: PRESS_GAP_CTL  > target_pressure

CloseN2VLV: Close nitrogen_valve


}

Press_Up --> [*]

}

@enduml